### ISSUE TITLE
system calls in Ruby script not working

### ISSUE THREAD

**Issue by ghost** [hdima/erlport#38]
I understand that if I'm going to be writing Elixir, I might as well use its method for calling system methods. But in the interest of reusing existing Ruby scripts, the first thing I tried after "hello world" is to make a 
system call with ruby.

I'm following the tutorial here: [Ruby code in Elixir project](https://medium.com/@Stephanbv/ruby-code-in-elixir-project-97614a9543d#.ep65vxb2m)

I have this elixir file:

```ex
defmodule RubyElixir.RubyCall do
  use Export.Ruby
  def ruby_call do
    {:ok, ruby} = Ruby.start(
      ruby_lib: Path.expand("lib/ruby")
    )
    ruby
    |> Ruby.call("ruby", "ruby_v", [])
  end
end
```

and this ruby file:

```rb
def ruby_v(name)
  puts system "ruby -v"
end
```

With either `system` or backticks, I get this error:

```txt
iex(1)> RubyElixir.RubyCall.ruby_call
** (ErlangError) erlang error: {:ruby, :IOError, "unsupported STDOUT operation for ErlPort", ["-e:1:in `<main>'", "/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'", "/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'", "/home/max/Elixir/ruby_elixir/_build/dev/lib/erlport/priv/ruby1.9/erlport/cli.rb:94:in `<top (required)>'", "/home/max/Elixir/ruby_elixir/_build/dev/lib/erlport/priv/ruby1.9/erlport/cli.rb:41:in `main'", "/home/max/Elixir/ruby_elixir/_build/dev/lib/erlport/priv/ruby1.9/erlport/erlang.rb:138:in `start'", "/home/max/Elixir/ruby_elixir/_build/dev/lib/erlport/priv/ruby1.9/erlport/erlang.rb:194:in `_receive'", "/home/max/Elixir/ruby_elixir/_build/dev/lib/erlport/priv/ruby1.9/erlport/erlang.rb:234:in `call_with_error_handler'", "/home/max/Elixir/ruby_elixir/_build/dev/lib/erlport/priv/ruby1.9/erlport/erlang.rb:195:in `block in _receive'", "/home/max/Elixir/ruby_elixir/_build/dev/lib/erlport/priv/ruby1.9/erlport/erlang.rb:221:in `incoming_call'", "/home/max/Elixir/ruby_elixir/lib/ruby/ruby.rb:2:in `ruby_v'", "/home/max/Elixir/ruby_elixir/lib/ruby/ruby.rb:2:in `system'", "/home/max/Elixir/ruby_elixir/_build/dev/lib/erlport/priv/ruby1.9/erlport/stdio.rb:59:in `method_missing'"]}
    (erlport) src/erlport.erl:234: :erlport.call/3

```

**Comment by mpinkston** [comment]
I think it's because `$stdout.flush` is getting called first, which isn't defined in the class ErlPort uses. It might be fixable by monkey-patching that class at the top of your script. (it worked in my case)

```ruby
module ErlPort
module StdIO
  class RedirectedStdout
    def flush
    end
  end
end
end
```
